# Generated by Django 4.1.5 on 2023-04-30 23:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookMng", "0003_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("book", "user")},
        ),
    ]
