# Generated by Django 4.1.5 on 2023-05-01 00:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookMng", "0005_alter_rating_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("book", "user")},
        ),
    ]
